name: action-test
on:
    push:
        branches: [master, test]
jobs:
    Build-New-Image:
        runs-on: ubuntu-latest
        env:
            BUILD_IMAGE: ${{ secrets.DOCKER_HUB_REPOSITORY }}:master
        steps:
            - uses: actions/checkout@v2
            - run: docker run --rm ${{ env.BUILD_IMAGE }} yarn typecheck
            - run: ./run_test.sh
