name: action-deploy
# on:
#     push:
#         branches: [master]
# jobs:
#     Deploy-New-Image:
#         runs-on: ubuntu-latest
#         env:
#             BUILD_IMAGE: ${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ github.head_ref }}
#             SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
#             SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
#             SSH_KEY_PATH: ${{ github.workspace }}/../private.key
#         steps:
#             - uses: actions/checkout@v2
#             - name: Create SSH key
#               run: |
#                   mkdir -p ~/.ssh/
#                   echo "$SSH_PRIVATE_KEY" > ../private.key
#                   sudo chmod 600 ../private.key
#                   echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
#               shell: bash
#             - run: ssh -i $SSH_KEY_PATH root@$SSH_HOST
#             - run: scp ./docker-compose.production.yaml root@sdc.beda.software:sdc-demo
#             - run: docker-compose -f docker-compose.production.yaml pull
#             - run: docker-compose -f docker-compose.production.yaml up -d
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Deploy to Server
              uses: easingthemes/ssh-deploy@v2.1.1
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  ARGS: '-rltgoDzvO --delete'
                  SOURCE: './examples/'
                  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                  REMOTE_USER: ${{ secrets.REMOTE_USER }}
                  TARGET: '/root/sdc-demo'
            - name: Restart
              uses: appleboy/ssh-action@master
              env:
                  ENV_FILE: ${{ secrets.ENV_FILE }}
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  username: ${{ secrets.REMOTE_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: 22
                  envs: ENV_FILE
                  script: |
                      cd /root/sdc-demo
                      echo -n $ENV_FILE|base64 -d > .env
                      docker-compose -f docker-compose.production.yaml pull
                      docker-compose -f docker-compose.production.yaml up -d
