name: action-deploy
on:
    push:
        branches: [master]
jobs:
    Deploy-New-Image:
        runs-on: ubuntu-latest
        env:
            BUILD_IMAGE: ${{ secrets.DOCKER_HUB_REPOSITORY }}:${GITHUB_REF#refs/heads/}
        steps:
            - run: ssh root@sdc.beda.software
            - run: scp ./docker-compose.production.yaml root@sdc.beda.software:sdc-demo
            - run: docker-compose -f docker-compose.production.yaml pull
            - run: docker-compose -f docker-compose.production.yaml up -d
