name: action-deploy
on:
    push:
        branches: [master]
jobs:
    Deploy-New-Image:
        runs-on: ubuntu-latest
        env:
            BUILD_IMAGE: ${{ secrets.DOCKER_HUB_REPOSITORY }}:${GITHUB_REF#refs/heads/}
        # steps:
        #     - name: Create SSH key
        #       run: |
        #           mkdir -p ~/.ssh/
        #           echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
        #           sudo chmod 600 ~/.ssh/private.key
        #           echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        #       shell: bash
        steps:
            - uses: actions/checkout@v2
            - name: Create SSH key
              run: |
                  mkdir -p ~/.ssh/
                  echo "$SSH_PRIVATE_KEY" > ../private.key
                  sudo chmod 600 ../private.key
                  echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
              shell: bash
              env:
                  SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
                  SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
                  SSH_KEY_PATH: ${{ github.workspace }}/../private.key
            #   env:
            #       SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
            #       SSH_HOST: ${{secrets.SSH_HOST}}
            #       SSH_KEY_PATH: ~/.ssh/private.key
            # - run: ssh -tt -v -i private root@sdc.beda.software
            - run: ssh -i $SSH_KEY_PATH root@$SSH_HOST
            - run: scp ./docker-compose.production.yaml root@sdc.beda.software:sdc-demo
            - run: docker-compose -f docker-compose.production.yaml pull
            - run: docker-compose -f docker-compose.production.yaml up -d
            # - name: Install SSH Key
            #   uses: shimataro/ssh-key-action@v2
            #   with:
            #   key: ${{ secrets.SSH_PRIVATE_KEY }}
            #   known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
            # - name: Adding Known Hosts
            #   run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
            # - name: Deploy with rsync
            #   run: ls -la
            #   run: rsync -avz ./root ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/root/sdc-demo/
